# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data-Term
description: > # this means to ignore newlines until "baseurl:"
  Статья с материалами по Мегакампании Rogues Gallery
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: /dataterm  # the subpath of your site, e.g. /blog
url: https://carengyl.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: carengyl
email: pavnikol84@gmail.com

navigation:
  - text: Home
    url: /
  - text: Найт-Сити
    url: /night-city

social:
  - service: vk
    username: Rogues Gallery
    link: https://vk.com/@geekmo-megakampaniya-cyberpunk-2020-v-geekmo-rogues-gallery
  - service: vk
    username: Geekmo
    link: https://vk.com/geekmo
  - service: rtalsorian
    username: R. Talsorian
    link: https://rtalsoriangames.com/cyberpunk/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Plugins
plugins:
  - jekyll-seo-tag